#!/usr/bin/env python3
"""Generate Baremetal-IDE test harnesses for the Atlas baremetal tests.

Source of truth stays in atlas-npu (never edited or copied):
  <atlas-dir>/assembly/<name>.S          Atlas program (+ inline @DRAM/@CHECK_DRAM/@PERF_* directives)
  <atlas-dir>/assembler.py               imported as a module: assemble(), golden/perf parsers
  <atlas-dir>/generators/gen_<name>.py   optional golden-data generator (stdout = JSON)

For each test this writes <out-dir>/atlas_<name>.c that performs the same steps, checks,
'*** PASSED ***' / '*** FAILED ***' messages and return codes as the harness emitted by
assembler.py's emit_c_file(), but drives the hardware through platform/penguin26's hal_atlas
driver instead of raw MMIO.

Generator lookup mirrors atlas-npu/baremetal/Makefile (rule `$(TESTS_DIR)/atlas_%.c`):
gen_<name>.py, else gen_<name with mxu[01]_ -> mxu_>.py, else no golden JSON (inline data only).
The generator runs with cwd = <atlas-dir>, like the Makefile. Golden JSON goes to
<json-dir> (default: <out-dir>/json), never into the atlas-npu tree.

usage:
  gen_atlas_tests.py --atlas-dir DIR --out-dir DIR [--json-dir DIR] [--python PY] (--all | NAME...)
  gen_atlas_tests.py --atlas-dir DIR --list          # print test names (one per line)
"""
import argparse
import glob
import io
import os
import re
import subprocess
import sys
from contextlib import redirect_stdout


def list_tests(atlas_dir):
    # Same set as the Makefile: $(wildcard $(ASM_DIR)/*.S) (top level only).
    return sorted(os.path.splitext(os.path.basename(p))[0]
                  for p in glob.glob(os.path.join(atlas_dir, "assembly", "*.S")))


def find_generator(atlas_dir, name):
    gen_dir = os.path.join(atlas_dir, "generators")
    cand = os.path.join(gen_dir, f"gen_{name}.py")
    if os.path.isfile(cand):
        return cand
    base = re.sub(r"mxu[01]_", "mxu_", name)   # Makefile: sed -E 's/mxu[01]_/mxu_/'
    cand = os.path.join(gen_dir, f"gen_{base}.py")
    if os.path.isfile(cand):
        return cand
    return None


def c_array(words, name, ctype="uint32_t", indent="    "):
    # Same formatting as assembler._fmt_array.
    lines = []
    for i in range(0, len(words), 8):
        chunk = words[i:i + 8]
        if ctype == "uint64_t":
            vals = ", ".join(f"0x{w & 0xFFFFFFFFFFFFFFFF:016X}ULL" for w in chunk)
        else:
            vals = ", ".join(f"0x{w & 0xFFFFFFFF:08X}U" for w in chunk)
        lines.append(f"{indent}{vals},")
    body = "\n".join(lines)
    return f"static const {ctype} {name}[] = {{\n{body}\n}};\n"


def emit_c(code, test_name, golden, perf_threshold, perf_report, macs0, macs1, src_desc):
    n = len(code)
    has_golden = golden is not None and (golden[1] or golden[3])

    out = f"""/* Auto-generated by Baremetal-IDE scripts/atlas/gen_atlas_tests.py -- DO NOT EDIT.
 * Test: {test_name}
 * {src_desc}
 * Same steps, checks, messages and return codes as the harness emitted by
 * atlas-npu/baremetal/assembler.py (emit_c_file), driven through platform/penguin26 hal_atlas.
 */
#include <stdio.h>
#include <stdint.h>

#include "chip_config.h"

#define ATLAS_PROGRAM_LEN {n}

"""
    out += c_array(code, "atlas_program")
    if has_golden:
        p_addrs, p_words, c_addrs, c_words = golden
        if p_words:
            out += f"#define PRELOAD_WORDS {len(p_words)}\n"
            out += c_array(p_addrs, "preload_addrs", ctype="uint64_t")
            out += c_array(p_words, "preload_data")
        if c_words:
            out += f"#define CHECK_WORDS   {len(c_words)}\n"
            out += c_array(c_addrs, "check_addrs", ctype="uint64_t")
            out += c_array(c_words, "check_expected")

    out += """
int main(void)
{
    int fail = 0;
"""
    if has_golden and golden[1]:
        out += """
    printf("Writing preload data to DRAM (%u words) ...\\n", PRELOAD_WORDS);
    atlas_mem_preload(preload_addrs, preload_data, PRELOAD_WORDS);
"""
    out += """
    printf("Stopping Atlas core before programming IMEM ...\\n");
    atlas_reset_for_load(ATLAS);

    printf("Writing program to ATLAS IMEM (%u words) ...\\n", ATLAS_PROGRAM_LEN);
    if (atlas_load_program(ATLAS_IMEM, atlas_program, ATLAS_PROGRAM_LEN) != 0) {
        printf("*** FAILED *** (program does not fit in IMEM)\\n");
        return 1;
    }

    printf("Reading back IMEM and verifying ...\\n");
    fail = (int)atlas_verify_program(ATLAS_IMEM, atlas_program, ATLAS_PROGRAM_LEN, 1);

    if (fail) {
        printf("*** FAILED *** (IMEM mismatch — %d words)\\n", fail);
        return 1;
    }
    printf("IMEM readback OK\\n");

    printf("Issuing Atlas START command ...\\n");
    atlas_start(ATLAS);
    atlas_fence();

    printf("Waiting for Atlas core to execute ...\\n");
    uint32_t dbg0 = atlas_wait_dbg0(ATLAS, ATLAS_DEFAULT_POLL_LIMIT);

    printf("Issuing Atlas STOP command ...\\n");
    atlas_stop(ATLAS);
    atlas_fence();

    uint32_t cycles   = atlas_get_cycles(ATLAS);
    uint32_t instcnt  = atlas_get_instret(ATLAS);
    uint32_t status   = atlas_get_status(ATLAS);

    printf("  DBG0    = %u\\n", dbg0);
    printf("  mcycles = %u\\n", cycles);
    printf("  minstret = %u\\n", instcnt);
    printf("  status  = 0x%08x\\n", status);

    if (dbg0 == 0) {
        printf("*** FAILED *** (timeout — Atlas core did not complete)\\n");
        return 1;
    }
"""
    if perf_threshold is not None or perf_report:
        out += """
    /* Perf metric. Denominator is the scalar-banked mcycles delta in CSR_DBG1. */
    uint32_t dbg1_cycles  = atlas_get_dbg1(ATLAS);
    printf("  dbg1_cycles  = %u\\n", dbg1_cycles);
"""
        if perf_threshold is not None:
            out += f"""
    if (dbg1_cycles == 0) {{
        printf("*** FAILED *** ({test_name} — dbg1_cycles == 0)\\n");
        return 1;
    }}
"""
        for mxu, macs in (("mxu0", macs0), ("mxu1", macs1)):
            if macs is None:
                continue
            out += f"""
    {{
        uint64_t macs = {macs}ULL;
        uint32_t util = dbg1_cycles ? (uint32_t)((macs * 100ULL) / (1024ULL * (uint64_t)dbg1_cycles)) : 0u;
        printf("  util_{mxu}    = %u%% (MACs=%llu, peak=1024 MAC/cyc)\\n",
               util, (unsigned long long)macs);
"""
            if perf_threshold is not None:
                out += f"""        if (util < {perf_threshold}u) {{
            printf("*** FAILED *** ({test_name} — util_{mxu} %u%% below threshold %u%%)\\n",
                   util, (unsigned){perf_threshold});
            return 1;
        }}
"""
            out += "    }\n"

    if has_golden and golden[3]:
        out += f"""
    printf("Verifying DRAM results (%u words) ...\\n", CHECK_WORDS);
    fail = (int)atlas_mem_check(check_addrs, check_expected, CHECK_WORDS, 1);

    if (fail) {{
        printf("*** FAILED *** (DRAM mismatch — %d words)\\n", fail);
        return 1;
    }}

    printf("*** PASSED *** ({test_name} — all DRAM checks passed)\\n");
    return 0;
}}
"""
    else:
        out += f"""
    if (dbg0 == 1) {{
        printf("*** PASSED *** ({test_name})\\n");
        return 0;
    }} else {{
        printf("*** FAILED *** ({test_name} dbg0=%u)\\n", dbg0);
        return 1;
    }}
}}
"""
    return out


def generate(asm_mod, atlas_dir, name, out_dir, json_dir, python):
    asm_path = os.path.join(atlas_dir, "assembly", f"{name}.S")
    with open(asm_path) as f:
        source = f.read()

    gen = find_generator(atlas_dir, name)
    golden = None
    if gen:
        os.makedirs(json_dir, exist_ok=True)
        json_path = os.path.join(json_dir, f"{name}.json")
        with open(json_path, "w") as jf:
            subprocess.run([python, gen], cwd=atlas_dir, stdout=jf, check=True)
        # assembler.main(): dram_base from '# @DRAM_BASE', else --dram-base default 0x0;
        # --beat-bytes default 32.
        dram_base = asm_mod._parse_dram_base(source)
        if dram_base is None:
            dram_base = 0
        golden = asm_mod._parse_golden_json(json_path, dram_base, 32)
        src_desc = f"Program: assembly/{name}.S; golden data: generators/{os.path.basename(gen)}"
    else:
        inline = asm_mod._parse_inline_golden(source, 32)
        if inline is not None:
            _, p_addrs, p_words, c_addrs, c_words = inline
            golden = (p_addrs, p_words, c_addrs, c_words)
        src_desc = f"Program: assembly/{name}.S (no golden generator; inline data only)"

    # assemble() may print diagnostics; keep them off our stdout.
    with redirect_stdout(io.StringIO()):
        code = asm_mod.assemble(source)
    perf_threshold = asm_mod._parse_perf_threshold(source)
    perf_report = asm_mod._parse_perf_report(source)
    macs0, macs1 = asm_mod._parse_perf_macs(source)

    c_src = emit_c(code, name, golden, perf_threshold, perf_report, macs0, macs1, src_desc)
    out_path = os.path.join(out_dir, f"atlas_{name}.c")
    old = None
    if os.path.exists(out_path):
        with open(out_path) as f:
            old = f.read()
    if old != c_src:   # don't touch mtime when unchanged (avoids needless rebuilds)
        with open(out_path, "w") as f:
            f.write(c_src)
    return out_path


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--atlas-dir", required=True, help="atlas-npu/baremetal directory")
    ap.add_argument("--out-dir", help="where atlas_<name>.c files are written")
    ap.add_argument("--json-dir", help="where golden JSON is written (default: <out-dir>/json)")
    ap.add_argument("--python", default=sys.executable,
                    help="interpreter for gen_*.py (needs numpy/torch/numba); default: this one")
    ap.add_argument("--all", action="store_true")
    ap.add_argument("--list", action="store_true")
    ap.add_argument("tests", nargs="*")
    args = ap.parse_args()

    atlas_dir = os.path.abspath(args.atlas_dir)
    if args.list:
        print("\n".join(list_tests(atlas_dir)))
        return 0
    if not args.out_dir:
        ap.error("--out-dir is required")
    names = list_tests(atlas_dir) if args.all else args.tests
    if not names:
        ap.error("give test names or --all")

    sys.path.insert(0, atlas_dir)
    import assembler as asm_mod  # noqa: E402  (atlas-npu/baremetal/assembler.py)

    out_dir = os.path.abspath(args.out_dir)
    json_dir = os.path.abspath(args.json_dir or os.path.join(out_dir, "json"))
    os.makedirs(out_dir, exist_ok=True)
    rc = 0
    for name in names:
        try:
            generate(asm_mod, atlas_dir, name, out_dir, json_dir, args.python)
        except Exception as e:  # report and keep going; the build of that target then fails
            print(f"gen_atlas_tests.py: {name}: {e}", file=sys.stderr)
            rc = 1
    return rc


if __name__ == "__main__":
    sys.exit(main())
